USE ESTUDIO_DE_CASO;


  CREATE TABLE AUTOMOVILES (
  ID_AUTOMOVILES INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
  KILOMETRAJE INT,
  MATRICULA varchar(6) DEFAULT NULL,
  MARCA varchar(30) NOT NULL,
  MODELO int NOT NULL,
  COLOR varchar(50) NOT NULL,
  PRECIO int NOT NULL,
  ID_CONCESIONARIO int NOT NULL);
  
  create TABLE concesionario (
  ID_CONCESIONARIO int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(100) NOT NULL,
  CORREO varchar(100) NOT NULL,
  TELEFONO int NOT NULL,
  DIRECCION varchar(100) NOT NULL);
  
  CREATE TABLE clientes (
  ID_CLIENTES int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  APELLIDO varchar(50) NOT NULL,
  NOMBRE varchar(50) NOT NULL,
  CORREO varchar(50) NOT NULL,
  FECHA_NACIMIENTO date DEFAULT NULL,
  TELEFONO int DEFAULT NULL,
  DIRECCION varchar(50) DEFAULT NULL);
  
  CREATE TABLE empleados(
  ID_EMPLEADO int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  APELLIDO varchar(50) NOT NULL,
  NOMBRE varchar(50) NOT NULL,
  CORREO varchar(50) NOT NULL,
  FECHA_NACIMIENTO date DEFAULT NULL,
  TELEFONO int DEFAULT NULL,
  DIRECCION varchar(50) DEFAULT NULL,
  USUARIO varchar(50) DEFAULT NULL);

CREATE TABLE referencia_venta (
  ID_REFVENTAS int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ID_EMPLEADO int NOT NULL,
  ID_CLIENTES int NOT NULL,
  ID_AUTOMOVILES int NOT NULL,
  FECHA_VENTA date DEFAULT NULL,
  PRECIO_FINAL int DEFAULT NULL,
  OBSERVACIONES varchar(3000) DEFAULT NULL);
  
  INSERT CONCESIONARIO
  
  INSERT INTO CONCESIONARIO VALUES(NULL, 'AUTOMOR','AUTOMOTOR@GMAIL.COM',5895591,'CARR-20·52');
  INSERT INTO CONCESIONARIO VALUES(NULL, 'MAXCAR','MAXICAR@GMAIL.COM',8547894,'CARR 12 20A');
  INSERT INTO CONCESIONARIO VALUES(NULL,'CAR-LOS','CARLOSCARROS@GMAIL.COM',587412,'CARR 13 NUM 56 A');
  INSERT INTO CONCESIONARIO VALUES(NULL,'CARROSYMAS','CARROSYMAS@GMAIL.COM',4587701,'CALLE 20-13-90');
  UPDATE CLIENTES SET FECHA_NACIMIENTO = '1970-02-06' WHERE ID_CLIENTES = 1;
  update automoviles set MODELO = 2023 where ID_AUTOMOVILES = 6;

 
  
  INSERT INTO CLIENTES VALUES(NULL,'MORENO','LUZ','LUZADRI@GMAIL.COM','2020-02-06',5896632,'CALLE 24-52-26');
  INSERT INTO CLIENTES VALUES(NULL,'DIAZ','JOSE','JOSEPH31@GMAIL.COM','1985-08-08',7894564,'CALLE 35-85-01B');
  INSERT INTO CLIENTES VALUES(NULL,'TORRES','DANIEL','DANIELTO45@GMAIL.COM','1967-05-09',8965547,'CARR 24-113C');
  INSERT INTO CLIENTES VALUES(NULL,'CORRALES','DANIELA','DANIELITA78@GMAIL.COM','1997-06-01',4569987,'CALLE 22A-39');
  INSERT INTO CLIENTES VALUES(NULL,'PEÑA','IVAN','IVANPENA@GMAIL.COM','1996-11-11',9852236,'CALLE 4-96-56');



INSERT INTO EMPLEADOS VALUES(NULL,'ARCINIEGAS','ANDRES','ANDRESAI@CONCESIONARIO.COM','1990-01-01',6927701,'CARR 22-56B','AANDRES');
INSERT INTO EMPLEADOS VALUES(NULL,'MORENO','ALEJANDRA','LUZ@CONCESIONARIO.COM','1997-01-02',9854412,'CARR 52-14-5B','AALEJ');
INSERT INTO EMPLEADOS VALUES(NULL,'DIAZ','DANIEL','DAN@CONCESIONARIO.COM','1998-05-04',7412563,'CARR 98-4C','DANIII');



INSERT INTO referencia_venta values (null,1,1,2,'2023-02-05','30000000','muy buen carro');
insert into referencia_venta values (null,2,2,2,'2023-05-01','30000000','excelento modelo');
insert into referencia_venta values (null,3,3,3,'2023-08-01','50000000','tenia daños en el motor');
